-- Script para crear las tablas de secciones de historias clínicas
-- Cada tabla está asociada a la tabla principal historias_clinicas

-- Tabla para la sección CUESTIONARIO
CREATE TABLE IF NOT EXISTS historias_clinicas_cuestionario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    tipo_examen VARCHAR(255),
    anamnesis TEXT,
    ultima_valoracion_optometria TEXT,
    ocupacion_profesion VARCHAR(255),
    antecedentes_familiares TEXT,
    antecedentes_personales TEXT,
    antecedentes_laborales TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección LENSOMETRÍA
CREATE TABLE IF NOT EXISTS historias_clinicas_lensometria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    formula_lejos_derecho_esfera VARCHAR(50),
    formula_lejos_derecho_cilindro VARCHAR(50),
    formula_lejos_derecho_eje VARCHAR(50),
    formula_lejos_derecho_adicion VARCHAR(50),
    formula_lejos_derecho_prisma VARCHAR(50),
    formula_lejos_izquierdo_esfera VARCHAR(50),
    formula_lejos_izquierdo_cilindro VARCHAR(50),
    formula_lejos_izquierdo_eje VARCHAR(50),
    formula_lejos_izquierdo_adicion VARCHAR(50),
    formula_lejos_izquierdo_prisma VARCHAR(50),
    formula_cerca_derecho_esfera VARCHAR(50),
    formula_cerca_derecho_cilindro VARCHAR(50),
    formula_cerca_derecho_eje VARCHAR(50),
    formula_cerca_derecho_adicion VARCHAR(50),
    formula_cerca_izquierdo_esfera VARCHAR(50),
    formula_cerca_izquierdo_cilindro VARCHAR(50),
    formula_cerca_izquierdo_eje VARCHAR(50),
    formula_cerca_izquierdo_adicion VARCHAR(50),
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección AGUDEZA VISUAL
CREATE TABLE IF NOT EXISTS historias_clinicas_agudeza_visual (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    lejos_test_usado VARCHAR(100),
    cerca_test_usado VARCHAR(100),
    sin_correccion_lejos_derecho VARCHAR(50),
    sin_correccion_lejos_izquierdo VARCHAR(50),
    sin_correccion_lejos_ambos VARCHAR(50),
    con_correccion_lejos_derecho VARCHAR(50),
    con_correccion_lejos_izquierdo VARCHAR(50),
    con_correccion_lejos_ambos VARCHAR(50),
    pin_hole_lejos_derecho VARCHAR(50),
    pin_hole_lejos_izquierdo VARCHAR(50),
    sin_correccion_cerca_derecho VARCHAR(50),
    sin_correccion_cerca_izquierdo VARCHAR(50),
    sin_correccion_cerca_ambos VARCHAR(50),
    sin_correccion_cerca_observacion TEXT,
    con_correccion_cerca_derecho VARCHAR(50),
    con_correccion_cerca_izquierdo VARCHAR(50),
    con_correccion_cerca_ambos VARCHAR(50),
    con_correccion_cerca_observacion TEXT,
    pin_hole_cerca_derecho VARCHAR(50),
    pin_hole_cerca_izquierdo VARCHAR(50),
    cerca_distancia VARCHAR(100),
    cerca_descripcion VARCHAR(100),
    cerca_derecho_sin_correccion VARCHAR(50),
    cerca_izquierdo_sin_correccion VARCHAR(50),
    cerca_observacion_sin_correccion TEXT,
    cerca_derecho_con_correccion VARCHAR(50),
    cerca_izquierdo_con_correccion VARCHAR(50),
    cerca_observacion_con_correccion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección EXAMEN MOTOR
CREATE TABLE IF NOT EXISTS historias_clinicas_examen_motor (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    mano_dominante VARCHAR(50),
    ojo_dominante VARCHAR(50),
    punto_proximo_valor VARCHAR(50),
    dp_lejos VARCHAR(50),
    dp_cerca VARCHAR(50),
    ducciones_derecho VARCHAR(100),
    ducciones_izquierdo VARCHAR(100),
    kappa_derecho VARCHAR(50),
    kappa_izquierdo VARCHAR(50),
    hirschberg VARCHAR(100),
    test_utilizado VARCHAR(100),
    cover_test_con_correccion_horizontal VARCHAR(50),
    cover_test_con_correccion_vertical VARCHAR(50),
    cover_test_sin_correccion_horizontal VARCHAR(50),
    cover_test_sin_correccion_vertical VARCHAR(50),
    prisma_con_correccion_horizontal VARCHAR(50),
    prisma_con_correccion_vertical VARCHAR(50),
    prisma_sin_correccion_horizontal VARCHAR(50),
    prisma_sin_correccion_vertical VARCHAR(50),
    observaciones TEXT,
    por_confirmar_derecho VARCHAR(100),
    por_confirmar_izquierdo VARCHAR(100),
    estereopsis_tipo VARCHAR(100),
    estereopsis_resultado VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección EXAMEN REFRACTIVO
CREATE TABLE IF NOT EXISTS historias_clinicas_examen_refractivo (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    -- Keratometría derecho
    keratometria_derecho_plano VARCHAR(50),
    keratometria_derecho_curvo VARCHAR(50),
    keratometria_derecho_eje VARCHAR(50),
    keratometria_derecho_miras VARCHAR(100),
    keratometria_derecho_corn VARCHAR(50),
    keratometria_derecho_esfera VARCHAR(50),
    keratometria_derecho_cilindro VARCHAR(50),
    keratometria_derecho_sombras VARCHAR(100),
    keratometria_derecho_av_lejos VARCHAR(50),
    keratometria_derecho_add VARCHAR(50),
    keratometria_derecho_av_cerca VARCHAR(50),
    keratometria_derecho_dnp VARCHAR(50),
    keratometria_derecho_vortice VARCHAR(50),
    keratometria_derecho_mm VARCHAR(50),
    keratometria_derecho_estatica VARCHAR(50),
    keratometria_derecho_dinamica VARCHAR(50),
    keratometria_derecho_normal VARCHAR(50),
    keratometria_derecho_cycloplejia VARCHAR(50),
    keratometria_derecho_otra VARCHAR(50),
    keratometria_derecho_distancia_al VARCHAR(50),
    keratometria_derecho_radio_k_1 VARCHAR(50),
    keratometria_derecho_radio_k_2 VARCHAR(50),
    keratometria_derecho_otra_refraccion VARCHAR(50),
    -- Keratometría izquierdo
    keratometria_izquierdo_plano VARCHAR(50),
    keratometria_izquierdo_curvo VARCHAR(50),
    keratometria_izquierdo_eje VARCHAR(50),
    keratometria_izquierdo_miras VARCHAR(100),
    keratometria_izquierdo_corn VARCHAR(50),
    keratometria_izquierdo_esfera VARCHAR(50),
    keratometria_izquierdo_cilindro VARCHAR(50),
    keratometria_izquierdo_sombras VARCHAR(100),
    keratometria_izquierdo_av_lejos VARCHAR(50),
    keratometria_izquierdo_add VARCHAR(50),
    keratometria_izquierdo_av_cerca VARCHAR(50),
    keratometria_izquierdo_dnp VARCHAR(50),
    keratometria_izquierdo_vortice VARCHAR(50),
    keratometria_izquierdo_mm VARCHAR(50),
    keratometria_izquierdo_estatica VARCHAR(50),
    keratometria_izquierdo_dinamica VARCHAR(50),
    keratometria_izquierdo_normal VARCHAR(50),
    keratometria_izquierdo_cycloplejia VARCHAR(50),
    keratometria_izquierdo_otra VARCHAR(50),
    keratometria_izquierdo_distancia_al VARCHAR(50),
    keratometria_izquierdo_radio_k_1 VARCHAR(50),
    keratometria_izquierdo_radio_k_2 VARCHAR(50),
    keratometria_izquierdo_otra_refraccion VARCHAR(50),
    -- Retinoscopía estática derecho
    retinoscopia_estatica_derecho_plano VARCHAR(50),
    retinoscopia_estatica_derecho_curvo VARCHAR(50),
    retinoscopia_estatica_derecho_eje VARCHAR(50),
    retinoscopia_estatica_derecho_miras VARCHAR(100),
    retinoscopia_estatica_derecho_corn VARCHAR(50),
    retinoscopia_estatica_derecho_esfera VARCHAR(50),
    retinoscopia_estatica_derecho_cilindro VARCHAR(50),
    retinoscopia_estatica_derecho_sombras VARCHAR(100),
    retinoscopia_estatica_derecho_av_lejos VARCHAR(50),
    retinoscopia_estatica_derecho_add VARCHAR(50),
    retinoscopia_estatica_derecho_av_cerca VARCHAR(50),
    retinoscopia_estatica_derecho_dnp VARCHAR(50),
    retinoscopia_estatica_derecho_vortice VARCHAR(50),
    retinoscopia_estatica_derecho_mm VARCHAR(50),
    retinoscopia_estatica_derecho_estatica VARCHAR(50),
    retinoscopia_estatica_derecho_dinamica VARCHAR(50),
    retinoscopia_estatica_derecho_normal VARCHAR(50),
    retinoscopia_estatica_derecho_cycloplejia VARCHAR(50),
    retinoscopia_estatica_derecho_otra VARCHAR(50),
    retinoscopia_estatica_derecho_distancia_al VARCHAR(50),
    retinoscopia_estatica_derecho_radio_k_1 VARCHAR(50),
    retinoscopia_estatica_derecho_radio_k_2 VARCHAR(50),
    retinoscopia_estatica_derecho_otra_refraccion VARCHAR(50),
    -- Retinoscopía estática izquierdo
    retinoscopia_estatica_izquierdo_plano VARCHAR(50),
    retinoscopia_estatica_izquierdo_curvo VARCHAR(50),
    retinoscopia_estatica_izquierdo_eje VARCHAR(50),
    retinoscopia_estatica_izquierdo_miras VARCHAR(100),
    retinoscopia_estatica_izquierdo_corn VARCHAR(50),
    retinoscopia_estatica_izquierdo_esfera VARCHAR(50),
    retinoscopia_estatica_izquierdo_cilindro VARCHAR(50),
    retinoscopia_estatica_izquierdo_sombras VARCHAR(100),
    retinoscopia_estatica_izquierdo_av_lejos VARCHAR(50),
    retinoscopia_estatica_izquierdo_add VARCHAR(50),
    retinoscopia_estatica_izquierdo_av_cerca VARCHAR(50),
    retinoscopia_estatica_izquierdo_dnp VARCHAR(50),
    retinoscopia_estatica_izquierdo_vortice VARCHAR(50),
    retinoscopia_estatica_izquierdo_mm VARCHAR(50),
    retinoscopia_estatica_izquierdo_estatica VARCHAR(50),
    retinoscopia_estatica_izquierdo_dinamica VARCHAR(50),
    retinoscopia_estatica_izquierdo_normal VARCHAR(50),
    retinoscopia_estatica_izquierdo_cycloplejia VARCHAR(50),
    retinoscopia_estatica_izquierdo_otra VARCHAR(50),
    retinoscopia_estatica_izquierdo_distancia_al VARCHAR(50),
    retinoscopia_estatica_izquierdo_radio_k_1 VARCHAR(50),
    retinoscopia_estatica_izquierdo_radio_k_2 VARCHAR(50),
    retinoscopia_estatica_izquierdo_otra_refraccion VARCHAR(50),
    -- Retinoscopía dinámica derecho
    retinoscopia_dinamica_derecho_plano VARCHAR(50),
    retinoscopia_dinamica_derecho_curvo VARCHAR(50),
    retinoscopia_dinamica_derecho_eje VARCHAR(50),
    retinoscopia_dinamica_derecho_miras VARCHAR(100),
    retinoscopia_dinamica_derecho_corn VARCHAR(50),
    retinoscopia_dinamica_derecho_esfera VARCHAR(50),
    retinoscopia_dinamica_derecho_cilindro VARCHAR(50),
    retinoscopia_dinamica_derecho_sombras VARCHAR(100),
    retinoscopia_dinamica_derecho_av_lejos VARCHAR(50),
    retinoscopia_dinamica_derecho_add VARCHAR(50),
    retinoscopia_dinamica_derecho_av_cerca VARCHAR(50),
    retinoscopia_dinamica_derecho_dnp VARCHAR(50),
    retinoscopia_dinamica_derecho_vortice VARCHAR(50),
    retinoscopia_dinamica_derecho_mm VARCHAR(50),
    retinoscopia_dinamica_derecho_estatica VARCHAR(50),
    retinoscopia_dinamica_derecho_dinamica VARCHAR(50),
    retinoscopia_dinamica_derecho_normal VARCHAR(50),
    retinoscopia_dinamica_derecho_cycloplejia VARCHAR(50),
    retinoscopia_dinamica_derecho_otra VARCHAR(50),
    retinoscopia_dinamica_derecho_distancia_al VARCHAR(50),
    retinoscopia_dinamica_derecho_radio_k_1 VARCHAR(50),
    retinoscopia_dinamica_derecho_radio_k_2 VARCHAR(50),
    retinoscopia_dinamica_derecho_otra_refraccion VARCHAR(50),
    -- Retinoscopía dinámica izquierdo
    retinoscopia_dinamica_izquierdo_plano VARCHAR(50),
    retinoscopia_dinamica_izquierdo_curvo VARCHAR(50),
    retinoscopia_dinamica_izquierdo_eje VARCHAR(50),
    retinoscopia_dinamica_izquierdo_miras VARCHAR(100),
    retinoscopia_dinamica_izquierdo_corn VARCHAR(50),
    retinoscopia_dinamica_izquierdo_esfera VARCHAR(50),
    retinoscopia_dinamica_izquierdo_cilindro VARCHAR(50),
    retinoscopia_dinamica_izquierdo_sombras VARCHAR(100),
    retinoscopia_dinamica_izquierdo_av_lejos VARCHAR(50),
    retinoscopia_dinamica_izquierdo_add VARCHAR(50),
    retinoscopia_dinamica_izquierdo_av_cerca VARCHAR(50),
    retinoscopia_dinamica_izquierdo_dnp VARCHAR(50),
    retinoscopia_dinamica_izquierdo_vortice VARCHAR(50),
    retinoscopia_dinamica_izquierdo_mm VARCHAR(50),
    retinoscopia_dinamica_izquierdo_estatica VARCHAR(50),
    retinoscopia_dinamica_izquierdo_dinamica VARCHAR(50),
    retinoscopia_dinamica_izquierdo_normal VARCHAR(50),
    retinoscopia_dinamica_izquierdo_cycloplejia VARCHAR(50),
    retinoscopia_dinamica_izquierdo_otra VARCHAR(50),
    retinoscopia_dinamica_izquierdo_distancia_al VARCHAR(50),
    retinoscopia_dinamica_izquierdo_radio_k_1 VARCHAR(50),
    retinoscopia_dinamica_izquierdo_radio_k_2 VARCHAR(50),
    retinoscopia_dinamica_izquierdo_otra_refraccion VARCHAR(50),
    -- Subjetivo derecho
    subjetivo_derecho_plano VARCHAR(50),
    subjetivo_derecho_curvo VARCHAR(50),
    subjetivo_derecho_eje VARCHAR(50),
    subjetivo_derecho_miras VARCHAR(100),
    subjetivo_derecho_corn VARCHAR(50),
    subjetivo_derecho_esfera VARCHAR(50),
    subjetivo_derecho_cilindro VARCHAR(50),
    subjetivo_derecho_sombras VARCHAR(100),
    subjetivo_derecho_av_lejos VARCHAR(50),
    subjetivo_derecho_add VARCHAR(50),
    subjetivo_derecho_av_cerca VARCHAR(50),
    subjetivo_derecho_dnp VARCHAR(50),
    subjetivo_derecho_vortice VARCHAR(50),
    subjetivo_derecho_mm VARCHAR(50),
    subjetivo_derecho_estatica VARCHAR(50),
    subjetivo_derecho_dinamica VARCHAR(50),
    subjetivo_derecho_normal VARCHAR(50),
    subjetivo_derecho_cycloplejia VARCHAR(50),
    subjetivo_derecho_otra VARCHAR(50),
    subjetivo_derecho_distancia_al VARCHAR(50),
    subjetivo_derecho_radio_k_1 VARCHAR(50),
    subjetivo_derecho_radio_k_2 VARCHAR(50),
    subjetivo_derecho_otra_refraccion VARCHAR(50),
    -- Subjetivo izquierdo
    subjetivo_izquierdo_plano VARCHAR(50),
    subjetivo_izquierdo_curvo VARCHAR(50),
    subjetivo_izquierdo_eje VARCHAR(50),
    subjetivo_izquierdo_miras VARCHAR(100),
    subjetivo_izquierdo_corn VARCHAR(50),
    subjetivo_izquierdo_esfera VARCHAR(50),
    subjetivo_izquierdo_cilindro VARCHAR(50),
    subjetivo_izquierdo_sombras VARCHAR(100),
    subjetivo_izquierdo_av_lejos VARCHAR(50),
    subjetivo_izquierdo_add VARCHAR(50),
    subjetivo_izquierdo_av_cerca VARCHAR(50),
    subjetivo_izquierdo_dnp VARCHAR(50),
    subjetivo_izquierdo_vortice VARCHAR(50),
    subjetivo_izquierdo_mm VARCHAR(50),
    subjetivo_izquierdo_estatica VARCHAR(50),
    subjetivo_izquierdo_dinamica VARCHAR(50),
    subjetivo_izquierdo_normal VARCHAR(50),
    subjetivo_izquierdo_cycloplejia VARCHAR(50),
    subjetivo_izquierdo_otra VARCHAR(50),
    subjetivo_izquierdo_distancia_al VARCHAR(50),
    subjetivo_izquierdo_radio_k_1 VARCHAR(50),
    subjetivo_izquierdo_radio_k_2 VARCHAR(50),
    subjetivo_izquierdo_otra_refraccion VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección EXAMEN OFTALMOLÓGICO
CREATE TABLE IF NOT EXISTS historias_clinicas_examen_oftalmologico (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    pupila_derecho VARCHAR(100),
    pupila_izquierdo VARCHAR(100),
    parpados_derecho VARCHAR(100),
    parpados_izquierdo VARCHAR(100),
    pelicula_lagrimal_derecho VARCHAR(100),
    pelicula_lagrimal_izquierdo VARCHAR(100),
    conjuntiva_derecho VARCHAR(100),
    conjuntiva_izquierdo VARCHAR(100),
    cornea_derecho VARCHAR(100),
    cornea_izquierdo VARCHAR(100),
    cristalino_derecho VARCHAR(100),
    cristalino_izquierdo VARCHAR(100),
    camara_anterior_derecho VARCHAR(100),
    camara_anterior_izquierdo VARCHAR(100),
    iris_derecho VARCHAR(100),
    iris_izquierdo VARCHAR(100),
    bruckner VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección OFTALMOSCOPIA
CREATE TABLE IF NOT EXISTS historias_clinicas_oftalmoscopia (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    derecho_excavacion DECIMAL(3,1),
    derecho_descripcion TEXT,
    izquierdo_excavacion DECIMAL(3,1),
    izquierdo_descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección FÓRMULA FINAL
CREATE TABLE IF NOT EXISTS historias_clinicas_formula_final (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    derecho_esfera VARCHAR(50),
    derecho_cilindro VARCHAR(50),
    derecho_eje VARCHAR(50),
    derecho_av_lejos VARCHAR(50),
    derecho_add VARCHAR(50),
    derecho_av_cerca VARCHAR(50),
    derecho_dnp INT,
    derecho_recomendacion TEXT,
    izquierdo_esfera VARCHAR(50),
    izquierdo_cilindro VARCHAR(50),
    izquierdo_eje VARCHAR(50),
    izquierdo_av_lejos VARCHAR(50),
    izquierdo_add VARCHAR(50),
    izquierdo_av_cerca VARCHAR(50),
    izquierdo_dnp INT,
    izquierdo_recomendacion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección OBSERVACIONES
CREATE TABLE IF NOT EXISTS historias_clinicas_observaciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    observaciones TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id)
);

-- Tabla para la sección DIAGNÓSTICO
CREATE TABLE IF NOT EXISTS historias_clinicas_diagnosticos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    historia_clinica_id INT NOT NULL,
    codigo VARCHAR(50),
    diagnostico VARCHAR(255),
    descripcion TEXT,
    ojo VARCHAR(50),
    principal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (historia_clinica_id) REFERENCES historias_clinicas(id) ON DELETE CASCADE,
    INDEX idx_historia_clinica_id (historia_clinica_id),
    INDEX idx_principal (principal)
);























